[package]
name = "codecrafters-git"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2024"
rust-version = "1.91"

[dependencies]
anyhow = "1"
bytes = "1"
flate2 = "1"
thiserror = "2"
clap = { version = "4", features = ["derive"] }
memmap2 = "0.9"
